#服务端口
server:
  port: 7005

#设置actuator开关
management:
  security:
    enabled: false

#config服务自身配置
spring:
  #应用名称
  application:
    name: phantom-server-config
  cloud:
    config:
      server:
        #配置git仓库信息
        git:
          uri: https://github.com/KingBoyWorld/{application}-conf
          username: kingboyworld
          password: kingboy123456
          default-label: master
          #更改本地临时缓存的目录
          #basedir: /root/config/git
  #rabbitmq配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#配置config服务的账号密码
security:
  user:
    name: kingboy
    password: 123456

#注册中心配置
eureka:
  auth:
    user: kingboy
    password: 123456
  client:
    service-url:
      defaultZone: http://${eureka.auth.user}:${eureka.auth.password}@localhost:7000/eureka/,http://${eureka.auth.user}:${eureka.auth.password}@eureka-master:7001/eureka/,http://${eureka.auth.user}:${eureka.auth.password}@eureka-slave:7002/eureka/
  instance:
    #使用IP进行注册
    prefer-ip-address: true
    #配置实例的注册ID
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    #心跳时间，即服务续约间隔时间（缺省为30s）
    lease-renewal-interval-in-seconds: 5
    #发呆时间，即服务续约到期时间（缺省为90s）
    lease-expiration-duration-in-seconds: 10


