server:
  port: 7002
eureka:
  instance:
    hostname: eureka-slave
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@eureka-master:7001/eureka/